-- ============================================
-- SEED — vacío
-- ============================================
-- El seed de datos se maneja con scripts TS:
--   npm run seed:estructura   → crea business + catálogo + equipo
--   npm run seed:operativo    → llena estado operativo (pedidos, mesas, caja)
--
-- Este archivo se ejecuta automáticamente en `supabase db reset` pero
-- no inserta nada por sí solo.
